# Generated by Django 5.1 on 2024-08-10 11:57

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=planetarium.models.astronomy_show_image_file_path,
            ),
        ),
    ]
